# Generated by Django 4.2.1 on 2023-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_category_product_images_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='worth',
            field=models.IntegerField(default=0),
        ),
    ]
