# Generated by Django 4.2.1 on 2023-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_price_product_worth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='home/images', default='static/home/questionmark.jpg'),
        ),
    ]
